//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBahus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISBahusEntities : DbContext
    {
        public ISBahusEntities()
            : base("name=ISBahusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IzvestajOStanjuRepromaterijala> IzvestajOStanjuRepromaterijalas { get; set; }
        public virtual DbSet<NalogZaProizvodnju> NalogZaProizvodnjus { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Sirovina> Sirovinas { get; set; }
        public virtual DbSet<StavkeIzvestajaOStanjuRepromaterijala> StavkeIzvestajaOStanjuRepromaterijalas { get; set; }
        public virtual DbSet<ZahtevOStanjuRepromaterijala> ZahtevOStanjuRepromaterijalas { get; set; }
    }
}
