//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBahus.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public enum Status { Nema,Nov, Izmenjen, Obrisan }
    public partial class IzvestajOStanjuRepromaterijala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzvestajOStanjuRepromaterijala()
        {
            this.StavkeIzvestajaOStanjuRepromaterijalas = new HashSet<StavkeIzvestajaOStanjuRepromaterijala>();
        }
    
        public int SifraIzvestaja { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> SifraZahteva { get; set; }
        public Nullable<int> Prima { get; set; }
        public Nullable<int> Izdaje { get; set; }
        public Status Status { get; set; }
        public virtual Radnik Radnik { get; set; }
        public virtual Radnik Radnik1 { get; set; }
        public virtual ZahtevOStanjuRepromaterijala ZahtevOStanjuRepromaterijala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkeIzvestajaOStanjuRepromaterijala> StavkeIzvestajaOStanjuRepromaterijalas { get; set; }

        int dajMaxID()
        {
            int max = 0;

            foreach (StavkeIzvestajaOStanjuRepromaterijala s in StavkeIzvestajaOStanjuRepromaterijalas)
            {
                if (s.RedniBroj > max) max = s.RedniBroj;
            }

            return max + 1;
        }

        public string dodajStavku(StavkeIzvestajaOStanjuRepromaterijala s)
        {
            s.RedniBroj = dajMaxID();
            s.IzvestajOStanjuRepromaterijala = null;
            s.SifraIzvestaja = this.SifraIzvestaja;
            StavkeIzvestajaOStanjuRepromaterijalas.Add(s);

            return "Stavka je uneta u listu stavki!";
        }

        public string izmeniStavku(StavkeIzvestajaOStanjuRepromaterijala s)
        {
            StavkeIzvestajaOStanjuRepromaterijalas.Remove(StavkeIzvestajaOStanjuRepromaterijalas.First(x => x.RedniBroj == s.RedniBroj));
            s.IzvestajOStanjuRepromaterijala = null;
            s.SifraIzvestaja = this.SifraIzvestaja;
            StavkeIzvestajaOStanjuRepromaterijalas.Add(s);

            return "Stavka je izmenjena!";
        }

        public string obrisiStavku(int id)
        {
            StavkeIzvestajaOStanjuRepromaterijalas.Remove(StavkeIzvestajaOStanjuRepromaterijalas.First(x => x.RedniBroj == id));

            return "Stavka je obrisana iz liste stavki!";
        }
    }
}
