//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBahus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Radnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radnik()
        {
            this.IzvestajOStanjuRepromaterijalas = new HashSet<IzvestajOStanjuRepromaterijala>();
            this.IzvestajOStanjuRepromaterijalas1 = new HashSet<IzvestajOStanjuRepromaterijala>();
            this.NalogZaProizvodnjus = new HashSet<NalogZaProizvodnju>();
            this.NalogZaProizvodnjus1 = new HashSet<NalogZaProizvodnju>();
            this.ZahtevOStanjuRepromaterijalas = new HashSet<ZahtevOStanjuRepromaterijala>();
            this.ZahtevOStanjuRepromaterijalas1 = new HashSet<ZahtevOStanjuRepromaterijala>();
        }
    
        public int SifraRadnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Profesija { get; set; }
        [DisplayName("Ime i prezime radnika")]
        public string PunoIme
        {
            get
            {
                return Ime + " " + Prezime;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzvestajOStanjuRepromaterijala> IzvestajOStanjuRepromaterijalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzvestajOStanjuRepromaterijala> IzvestajOStanjuRepromaterijalas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NalogZaProizvodnju> NalogZaProizvodnjus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NalogZaProizvodnju> NalogZaProizvodnjus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtevOStanjuRepromaterijala> ZahtevOStanjuRepromaterijalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZahtevOStanjuRepromaterijala> ZahtevOStanjuRepromaterijalas1 { get; set; }
    }
}
