//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBahus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkeIzvestajaOStanjuRepromaterijala
    {
        public int SifraIzvestaja { get; set; }
        public int RedniBroj { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> SifraSirovine { get; set; }
    
        public virtual IzvestajOStanjuRepromaterijala IzvestajOStanjuRepromaterijala { get; set; }
        public virtual Sirovina Sirovina { get; set; }
    }
}
